# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'can_unit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(760, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(750, 250))
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameLine = QtWidgets.QLineEdit(Frame)
        self.nameLine.setGeometry(QtCore.QRect(40, 0, 281, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLine.sizePolicy().hasHeightForWidth())
        self.nameLine.setSizePolicy(sizePolicy)
        self.nameLine.setMinimumSize(QtCore.QSize(0, 30))
        self.nameLine.setObjectName("nameLine")
        self.dataTable = QtWidgets.QTableWidget(Frame)
        self.dataTable.setGeometry(QtCore.QRect(330, 0, 421, 241))
        self.dataTable.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dataTable.setFont(font)
        self.dataTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setRowCount(8)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setItem(0, 0, item)
        self.dataTable.horizontalHeader().setDefaultSectionSize(47)
        self.dataTable.horizontalHeader().setMinimumSectionSize(47)
        self.dataTable.verticalHeader().setDefaultSectionSize(25)
        self.dataTable.verticalHeader().setMinimumSectionSize(25)
        self.numLabel = QtWidgets.QLabel(Frame)
        self.numLabel.setGeometry(QtCore.QRect(0, 0, 31, 25))
        self.numLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.numLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numLabel.setObjectName("numLabel")
        self.line = QtWidgets.QFrame(Frame)
        self.line.setGeometry(QtCore.QRect(10, 240, 741, 10))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 311, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.devIDLabel = QtWidgets.QLabel(self.layoutWidget)
        self.devIDLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.devIDLabel.setObjectName("devIDLabel")
        self.horizontalLayout.addWidget(self.devIDLabel)
        self.devIDSBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.devIDSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.devIDSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.devIDSBox.setMinimum(1)
        self.devIDSBox.setMaximum(32)
        self.devIDSBox.setProperty("value", 6)
        self.devIDSBox.setObjectName("devIDSBox")
        self.horizontalLayout.addWidget(self.devIDSBox)
        self.varIDLabel = QtWidgets.QLabel(self.layoutWidget)
        self.varIDLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.varIDLabel.setObjectName("varIDLabel")
        self.horizontalLayout.addWidget(self.varIDLabel)
        self.varIDSBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.varIDSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.varIDSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.varIDSBox.setMinimum(0)
        self.varIDSBox.setMaximum(32)
        self.varIDSBox.setProperty("value", 5)
        self.varIDSBox.setObjectName("varIDSBox")
        self.horizontalLayout.addWidget(self.varIDSBox)
        self.layoutWidget1 = QtWidgets.QWidget(Frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 120, 311, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.offsetLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.offsetLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.offsetLabel.setObjectName("offsetLabel")
        self.horizontalLayout_2.addWidget(self.offsetLabel)
        self.offsetSBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.offsetSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.offsetSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offsetSBox.setMaximum(2048)
        self.offsetSBox.setObjectName("offsetSBox")
        self.horizontalLayout_2.addWidget(self.offsetSBox)
        self.lengthLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.lengthLabel.setObjectName("lengthLabel")
        self.horizontalLayout_2.addWidget(self.lengthLabel)
        self.lengthSBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.lengthSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.lengthSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lengthSBox.setMinimum(1)
        self.lengthSBox.setMaximum(128)
        self.lengthSBox.setProperty("value", 128)
        self.lengthSBox.setObjectName("lengthSBox")
        self.horizontalLayout_2.addWidget(self.lengthSBox)
        self.layoutWidget2 = QtWidgets.QWidget(Frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 160, 311, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.idVarLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.idVarLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.idVarLabel.setObjectName("idVarLabel")
        self.horizontalLayout_3.addWidget(self.idVarLabel)
        self.idVarLine = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idVarLine.sizePolicy().hasHeightForWidth())
        self.idVarLine.setSizePolicy(sizePolicy)
        self.idVarLine.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.idVarLine.setFont(font)
        self.idVarLine.setReadOnly(False)
        self.idVarLine.setObjectName("idVarLine")
        self.horizontalLayout_3.addWidget(self.idVarLine)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.layoutWidget3 = QtWidgets.QWidget(Frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 200, 311, 36))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.modeBox = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeBox.sizePolicy().hasHeightForWidth())
        self.modeBox.setSizePolicy(sizePolicy)
        self.modeBox.setMinimumSize(QtCore.QSize(100, 30))
        self.modeBox.setObjectName("modeBox")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.horizontalLayout_4.addWidget(self.modeBox)
        self.actionPButton = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionPButton.sizePolicy().hasHeightForWidth())
        self.actionPButton.setSizePolicy(sizePolicy)
        self.actionPButton.setMinimumSize(QtCore.QSize(80, 30))
        self.actionPButton.setObjectName("actionPButton")
        self.horizontalLayout_4.addWidget(self.actionPButton)
        self.layoutWidget4 = QtWidgets.QWidget(Frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 40, 311, 32))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CANChanNUMLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.CANChanNUMLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.CANChanNUMLabel.setObjectName("CANChanNUMLabel")
        self.horizontalLayout_5.addWidget(self.CANChanNUMLabel)
        self.CANChanNUMSBox = QtWidgets.QSpinBox(self.layoutWidget4)
        self.CANChanNUMSBox.setMinimumSize(QtCore.QSize(50, 30))
        self.CANChanNUMSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CANChanNUMSBox.setMaximum(1)
        self.CANChanNUMSBox.setObjectName("CANChanNUMSBox")
        self.horizontalLayout_5.addWidget(self.CANChanNUMSBox)
        self.statusLabel = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_5.addWidget(self.statusLabel)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.nameLine, self.devIDSBox)
        Frame.setTabOrder(self.devIDSBox, self.varIDSBox)
        Frame.setTabOrder(self.varIDSBox, self.lengthSBox)
        Frame.setTabOrder(self.lengthSBox, self.idVarLine)
        Frame.setTabOrder(self.idVarLine, self.modeBox)
        Frame.setTabOrder(self.modeBox, self.actionPButton)
        Frame.setTabOrder(self.actionPButton, self.dataTable)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        item = self.dataTable.verticalHeaderItem(0)
        item.setText(_translate("Frame", "+0"))
        item = self.dataTable.verticalHeaderItem(1)
        item.setText(_translate("Frame", "+8"))
        item = self.dataTable.verticalHeaderItem(2)
        item.setText(_translate("Frame", "+16"))
        item = self.dataTable.verticalHeaderItem(3)
        item.setText(_translate("Frame", "+24"))
        item = self.dataTable.verticalHeaderItem(4)
        item.setText(_translate("Frame", "+32"))
        item = self.dataTable.verticalHeaderItem(5)
        item.setText(_translate("Frame", "+40"))
        item = self.dataTable.verticalHeaderItem(6)
        item.setText(_translate("Frame", "+48"))
        item = self.dataTable.verticalHeaderItem(7)
        item.setText(_translate("Frame", "+56"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "0"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "1"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "2"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "3"))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "4"))
        item = self.dataTable.horizontalHeaderItem(5)
        item.setText(_translate("Frame", "5"))
        item = self.dataTable.horizontalHeaderItem(6)
        item.setText(_translate("Frame", "6"))
        item = self.dataTable.horizontalHeaderItem(7)
        item.setText(_translate("Frame", "7"))
        __sortingEnabled = self.dataTable.isSortingEnabled()
        self.dataTable.setSortingEnabled(False)
        item = self.dataTable.item(0, 0)
        item.setText(_translate("Frame", "0000"))
        self.dataTable.setSortingEnabled(__sortingEnabled)
        self.numLabel.setText(_translate("Frame", "0"))
        self.devIDLabel.setText(_translate("Frame", "Dev ID:"))
        self.varIDLabel.setText(_translate("Frame", "Var ID:"))
        self.offsetLabel.setText(_translate("Frame", "Offset:"))
        self.lengthLabel.setText(_translate("Frame", "Length:"))
        self.idVarLabel.setText(_translate("Frame", "ID Var: "))
        self.modeBox.setItemText(0, _translate("Frame", "Чтение"))
        self.modeBox.setItemText(1, _translate("Frame", "Запись"))
        self.actionPButton.setText(_translate("Frame", "Пуск"))
        self.CANChanNUMLabel.setText(_translate("Frame", "CAN channel №:"))
        self.statusLabel.setText(_translate("Frame", "Статус"))
