# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'can_unit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(824, 245)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(810, 245))
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setContentsMargins(0, 0, 5, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.numLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel.sizePolicy().hasHeightForWidth())
        self.numLabel.setSizePolicy(sizePolicy)
        self.numLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.numLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numLabel.setObjectName("numLabel")
        self.horizontalLayout_6.addWidget(self.numLabel)
        self.nameLine = QtWidgets.QLineEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLine.sizePolicy().hasHeightForWidth())
        self.nameLine.setSizePolicy(sizePolicy)
        self.nameLine.setMinimumSize(QtCore.QSize(0, 30))
        self.nameLine.setObjectName("nameLine")
        self.horizontalLayout_6.addWidget(self.nameLine)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CANChanNUMLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CANChanNUMLabel.sizePolicy().hasHeightForWidth())
        self.CANChanNUMLabel.setSizePolicy(sizePolicy)
        self.CANChanNUMLabel.setMinimumSize(QtCore.QSize(115, 30))
        self.CANChanNUMLabel.setObjectName("CANChanNUMLabel")
        self.horizontalLayout_5.addWidget(self.CANChanNUMLabel)
        self.CANChanNUMSBox = QtWidgets.QSpinBox(Frame)
        self.CANChanNUMSBox.setMinimumSize(QtCore.QSize(50, 30))
        self.CANChanNUMSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CANChanNUMSBox.setMaximum(1)
        self.CANChanNUMSBox.setObjectName("CANChanNUMSBox")
        self.horizontalLayout_5.addWidget(self.CANChanNUMSBox)
        self.statusLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setMinimumSize(QtCore.QSize(50, 25))
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_5.addWidget(self.statusLabel)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.devIDLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devIDLabel.sizePolicy().hasHeightForWidth())
        self.devIDLabel.setSizePolicy(sizePolicy)
        self.devIDLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.devIDLabel.setObjectName("devIDLabel")
        self.horizontalLayout.addWidget(self.devIDLabel)
        self.devIDSBox = QtWidgets.QSpinBox(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devIDSBox.sizePolicy().hasHeightForWidth())
        self.devIDSBox.setSizePolicy(sizePolicy)
        self.devIDSBox.setMinimumSize(QtCore.QSize(60, 30))
        self.devIDSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.devIDSBox.setMinimum(1)
        self.devIDSBox.setMaximum(32)
        self.devIDSBox.setProperty("value", 6)
        self.devIDSBox.setObjectName("devIDSBox")
        self.horizontalLayout.addWidget(self.devIDSBox)
        self.varIDLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varIDLabel.sizePolicy().hasHeightForWidth())
        self.varIDLabel.setSizePolicy(sizePolicy)
        self.varIDLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.varIDLabel.setObjectName("varIDLabel")
        self.horizontalLayout.addWidget(self.varIDLabel)
        self.varIDSBox = QtWidgets.QSpinBox(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varIDSBox.sizePolicy().hasHeightForWidth())
        self.varIDSBox.setSizePolicy(sizePolicy)
        self.varIDSBox.setMinimumSize(QtCore.QSize(60, 30))
        self.varIDSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.varIDSBox.setMinimum(0)
        self.varIDSBox.setMaximum(32)
        self.varIDSBox.setProperty("value", 5)
        self.varIDSBox.setObjectName("varIDSBox")
        self.horizontalLayout.addWidget(self.varIDSBox)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.offsetLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetLabel.sizePolicy().hasHeightForWidth())
        self.offsetLabel.setSizePolicy(sizePolicy)
        self.offsetLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.offsetLabel.setObjectName("offsetLabel")
        self.horizontalLayout_2.addWidget(self.offsetLabel)
        self.offsetSBox = QtWidgets.QSpinBox(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetSBox.sizePolicy().hasHeightForWidth())
        self.offsetSBox.setSizePolicy(sizePolicy)
        self.offsetSBox.setMinimumSize(QtCore.QSize(60, 30))
        self.offsetSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offsetSBox.setMaximum(100000000)
        self.offsetSBox.setObjectName("offsetSBox")
        self.horizontalLayout_2.addWidget(self.offsetSBox)
        self.lengthLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengthLabel.sizePolicy().hasHeightForWidth())
        self.lengthLabel.setSizePolicy(sizePolicy)
        self.lengthLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.lengthLabel.setObjectName("lengthLabel")
        self.horizontalLayout_2.addWidget(self.lengthLabel)
        self.lengthSBox = QtWidgets.QSpinBox(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengthSBox.sizePolicy().hasHeightForWidth())
        self.lengthSBox.setSizePolicy(sizePolicy)
        self.lengthSBox.setMinimumSize(QtCore.QSize(60, 30))
        self.lengthSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lengthSBox.setMinimum(1)
        self.lengthSBox.setMaximum(128)
        self.lengthSBox.setProperty("value", 128)
        self.lengthSBox.setObjectName("lengthSBox")
        self.horizontalLayout_2.addWidget(self.lengthSBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.idVarLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idVarLabel.sizePolicy().hasHeightForWidth())
        self.idVarLabel.setSizePolicy(sizePolicy)
        self.idVarLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.idVarLabel.setObjectName("idVarLabel")
        self.horizontalLayout_3.addWidget(self.idVarLabel)
        self.idVarLine = QtWidgets.QLineEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idVarLine.sizePolicy().hasHeightForWidth())
        self.idVarLine.setSizePolicy(sizePolicy)
        self.idVarLine.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.idVarLine.setFont(font)
        self.idVarLine.setReadOnly(False)
        self.idVarLine.setObjectName("idVarLine")
        self.horizontalLayout_3.addWidget(self.idVarLine)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.modeBox = QtWidgets.QComboBox(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeBox.sizePolicy().hasHeightForWidth())
        self.modeBox.setSizePolicy(sizePolicy)
        self.modeBox.setMinimumSize(QtCore.QSize(100, 30))
        self.modeBox.setObjectName("modeBox")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.horizontalLayout_4.addWidget(self.modeBox)
        self.actionPButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionPButton.sizePolicy().hasHeightForWidth())
        self.actionPButton.setSizePolicy(sizePolicy)
        self.actionPButton.setMinimumSize(QtCore.QSize(50, 30))
        self.actionPButton.setObjectName("actionPButton")
        self.horizontalLayout_4.addWidget(self.actionPButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Frame)
        self.line.setMinimumSize(QtCore.QSize(750, 5))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.dataTable = QtWidgets.QTableWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setMinimumSize(QtCore.QSize(540, 150))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dataTable.setFont(font)
        self.dataTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.dataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setWordWrap(False)
        self.dataTable.setRowCount(8)
        self.dataTable.setColumnCount(16)
        self.dataTable.setObjectName("dataTable")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(5)
        item.setFont(font)
        self.dataTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.dataTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setItem(0, 0, item)
        self.dataTable.horizontalHeader().setVisible(True)
        self.dataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.dataTable.horizontalHeader().setDefaultSectionSize(30)
        self.dataTable.horizontalHeader().setMinimumSectionSize(30)
        self.dataTable.horizontalHeader().setSortIndicatorShown(False)
        self.dataTable.horizontalHeader().setStretchLastSection(False)
        self.dataTable.verticalHeader().setDefaultSectionSize(30)
        self.dataTable.verticalHeader().setMinimumSectionSize(30)
        self.dataTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.dataTable, 0, 1, 1, 2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.nameLine, self.devIDSBox)
        Frame.setTabOrder(self.devIDSBox, self.varIDSBox)
        Frame.setTabOrder(self.varIDSBox, self.lengthSBox)
        Frame.setTabOrder(self.lengthSBox, self.idVarLine)
        Frame.setTabOrder(self.idVarLine, self.modeBox)
        Frame.setTabOrder(self.modeBox, self.actionPButton)
        Frame.setTabOrder(self.actionPButton, self.dataTable)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.numLabel.setText(_translate("Frame", "0"))
        self.CANChanNUMLabel.setText(_translate("Frame", "CAN channel №:"))
        self.statusLabel.setText(_translate("Frame", "Статус"))
        self.devIDLabel.setText(_translate("Frame", "Dev ID:"))
        self.varIDLabel.setText(_translate("Frame", "Var ID:"))
        self.offsetLabel.setText(_translate("Frame", "Offset:"))
        self.lengthLabel.setText(_translate("Frame", "Length:"))
        self.idVarLabel.setText(_translate("Frame", "ID Var: "))
        self.modeBox.setItemText(0, _translate("Frame", "Чтение"))
        self.modeBox.setItemText(1, _translate("Frame", "Запись"))
        self.actionPButton.setText(_translate("Frame", "Пуск"))
        item = self.dataTable.verticalHeaderItem(0)
        item.setText(_translate("Frame", "+0"))
        item = self.dataTable.verticalHeaderItem(1)
        item.setText(_translate("Frame", "+16"))
        item = self.dataTable.verticalHeaderItem(2)
        item.setText(_translate("Frame", "+32"))
        item = self.dataTable.verticalHeaderItem(3)
        item.setText(_translate("Frame", "+48"))
        item = self.dataTable.verticalHeaderItem(4)
        item.setText(_translate("Frame", "+64"))
        item = self.dataTable.verticalHeaderItem(5)
        item.setText(_translate("Frame", "+80"))
        item = self.dataTable.verticalHeaderItem(6)
        item.setText(_translate("Frame", "+96"))
        item = self.dataTable.verticalHeaderItem(7)
        item.setText(_translate("Frame", "+112"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "0"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "1"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "2"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "3"))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "4"))
        item = self.dataTable.horizontalHeaderItem(5)
        item.setText(_translate("Frame", "5"))
        item = self.dataTable.horizontalHeaderItem(6)
        item.setText(_translate("Frame", "6"))
        item = self.dataTable.horizontalHeaderItem(7)
        item.setText(_translate("Frame", "7"))
        item = self.dataTable.horizontalHeaderItem(8)
        item.setText(_translate("Frame", "8"))
        item = self.dataTable.horizontalHeaderItem(9)
        item.setText(_translate("Frame", "9"))
        item = self.dataTable.horizontalHeaderItem(10)
        item.setText(_translate("Frame", "10"))
        item = self.dataTable.horizontalHeaderItem(11)
        item.setText(_translate("Frame", "11"))
        item = self.dataTable.horizontalHeaderItem(12)
        item.setText(_translate("Frame", "12"))
        item = self.dataTable.horizontalHeaderItem(13)
        item.setText(_translate("Frame", "13"))
        item = self.dataTable.horizontalHeaderItem(14)
        item.setText(_translate("Frame", "14"))
        item = self.dataTable.horizontalHeaderItem(15)
        item.setText(_translate("Frame", "15"))
        __sortingEnabled = self.dataTable.isSortingEnabled()
        self.dataTable.setSortingEnabled(False)
        item = self.dataTable.item(0, 0)
        item.setText(_translate("Frame", "00"))
        self.dataTable.setSortingEnabled(__sortingEnabled)
