# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusLEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLEdit.sizePolicy().hasHeightForWidth())
        self.statusLEdit.setSizePolicy(sizePolicy)
        self.statusLEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.statusLEdit.setObjectName("statusLEdit")
        self.horizontalLayout.addWidget(self.statusLEdit)
        self.openGraphPButton = QtWidgets.QPushButton(self.centralwidget)
        self.openGraphPButton.setObjectName("openGraphPButton")
        self.horizontalLayout.addWidget(self.openGraphPButton)
        self.logRestartPButt = QtWidgets.QPushButton(self.centralwidget)
        self.logRestartPButt.setObjectName("logRestartPButt")
        self.horizontalLayout.addWidget(self.logRestartPButt)
        self.connectionPButt = QtWidgets.QPushButton(self.centralwidget)
        self.connectionPButt.setMinimumSize(QtCore.QSize(60, 30))
        self.connectionPButt.setObjectName("connectionPButt")
        self.horizontalLayout.addWidget(self.connectionPButt)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 1, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_4 = QtWidgets.QFrame(self.mainTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.channelGrBox = QtWidgets.QGroupBox(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelGrBox.sizePolicy().hasHeightForWidth())
        self.channelGrBox.setSizePolicy(sizePolicy)
        self.channelGrBox.setMinimumSize(QtCore.QSize(250, 0))
        self.channelGrBox.setObjectName("channelGrBox")
        self.gridLayout = QtWidgets.QGridLayout(self.channelGrBox)
        self.gridLayout.setObjectName("gridLayout")
        self.allChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.allChannelsChBox.setObjectName("allChannelsChBox")
        self.gridLayout.addWidget(self.allChannelsChBox, 0, 0, 1, 1)
        self.pl11aChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.pl11aChannelsChBox.setChecked(True)
        self.pl11aChannelsChBox.setObjectName("pl11aChannelsChBox")
        self.gridLayout.addWidget(self.pl11aChannelsChBox, 1, 0, 1, 1)
        self.pl11bChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.pl11bChannelsChBox.setObjectName("pl11bChannelsChBox")
        self.gridLayout.addWidget(self.pl11bChannelsChBox, 2, 0, 1, 1)
        self.pl12ChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.pl12ChannelsChBox.setObjectName("pl12ChannelsChBox")
        self.gridLayout.addWidget(self.pl12ChannelsChBox, 3, 0, 1, 1)
        self.lmChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.lmChannelsChBox.setObjectName("lmChannelsChBox")
        self.gridLayout.addWidget(self.lmChannelsChBox, 0, 1, 1, 1)
        self.pl20ChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.pl20ChannelsChBox.setObjectName("pl20ChannelsChBox")
        self.gridLayout.addWidget(self.pl20ChannelsChBox, 1, 1, 1, 1)
        self.dcr1ChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.dcr1ChannelsChBox.setObjectName("dcr1ChannelsChBox")
        self.gridLayout.addWidget(self.dcr1ChannelsChBox, 2, 1, 1, 1)
        self.dcr2ChannelsChBox = QtWidgets.QCheckBox(self.channelGrBox)
        self.dcr2ChannelsChBox.setObjectName("dcr2ChannelsChBox")
        self.gridLayout.addWidget(self.dcr2ChannelsChBox, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.channelGrBox)
        self.pwrChsSetPButton = QtWidgets.QPushButton(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwrChsSetPButton.sizePolicy().hasHeightForWidth())
        self.pwrChsSetPButton.setSizePolicy(sizePolicy)
        self.pwrChsSetPButton.setObjectName("pwrChsSetPButton")
        self.verticalLayout.addWidget(self.pwrChsSetPButton)
        self.line_2 = QtWidgets.QFrame(self.mainTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stopCyclsPButton = QtWidgets.QPushButton(self.mainTab)
        self.stopCyclsPButton.setObjectName("stopCyclsPButton")
        self.gridLayout_3.addWidget(self.stopCyclsPButton, 4, 0, 1, 3)
        self.startCyclsPButton = QtWidgets.QPushButton(self.mainTab)
        self.startCyclsPButton.setObjectName("startCyclsPButton")
        self.gridLayout_3.addWidget(self.startCyclsPButton, 3, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.mainTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 1, 0, 1, 3)
        self.singleCyclSBox = QtWidgets.QSpinBox(self.mainTab)
        self.singleCyclSBox.setMinimumSize(QtCore.QSize(50, 30))
        self.singleCyclSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.singleCyclSBox.setObjectName("singleCyclSBox")
        self.gridLayout_3.addWidget(self.singleCyclSBox, 2, 2, 1, 1)
        self.singleCyclPButton = QtWidgets.QPushButton(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleCyclPButton.sizePolicy().hasHeightForWidth())
        self.singleCyclPButton.setSizePolicy(sizePolicy)
        self.singleCyclPButton.setMinimumSize(QtCore.QSize(60, 0))
        self.singleCyclPButton.setObjectName("singleCyclPButton")
        self.gridLayout_3.addWidget(self.singleCyclPButton, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_8 = QtWidgets.QFrame(self.mainTab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        spacerItem1 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.mainTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_6 = QtWidgets.QFrame(self.mainTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.genDataGetPButton = QtWidgets.QPushButton(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genDataGetPButton.sizePolicy().hasHeightForWidth())
        self.genDataGetPButton.setSizePolicy(sizePolicy)
        self.genDataGetPButton.setObjectName("genDataGetPButton")
        self.verticalLayout.addWidget(self.genDataGetPButton)
        self.cycleReadGenDataPButton = QtWidgets.QPushButton(self.mainTab)
        self.cycleReadGenDataPButton.setObjectName("cycleReadGenDataPButton")
        self.verticalLayout.addWidget(self.cycleReadGenDataPButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(1500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pl11AIKUGBoxGrBox = QtWidgets.QGroupBox(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl11AIKUGBoxGrBox.sizePolicy().hasHeightForWidth())
        self.pl11AIKUGBoxGrBox.setSizePolicy(sizePolicy)
        self.pl11AIKUGBoxGrBox.setMinimumSize(QtCore.QSize(250, 0))
        self.pl11AIKUGBoxGrBox.setObjectName("pl11AIKUGBoxGrBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pl11AIKUGBoxGrBox)
        self.gridLayout_9.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_9.setSpacing(5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pl11AResetFPGAChBox = QtWidgets.QCheckBox(self.pl11AIKUGBoxGrBox)
        self.pl11AResetFPGAChBox.setChecked(True)
        self.pl11AResetFPGAChBox.setObjectName("pl11AResetFPGAChBox")
        self.gridLayout_9.addWidget(self.pl11AResetFPGAChBox, 0, 0, 1, 1)
        self.pl11AResetMCUChBox = QtWidgets.QCheckBox(self.pl11AIKUGBoxGrBox)
        self.pl11AResetMCUChBox.setChecked(True)
        self.pl11AResetMCUChBox.setObjectName("pl11AResetMCUChBox")
        self.gridLayout_9.addWidget(self.pl11AResetMCUChBox, 0, 1, 1, 1)
        self.pl11ASetIKUPButton = QtWidgets.QPushButton(self.pl11AIKUGBoxGrBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl11ASetIKUPButton.sizePolicy().hasHeightForWidth())
        self.pl11ASetIKUPButton.setSizePolicy(sizePolicy)
        self.pl11ASetIKUPButton.setObjectName("pl11ASetIKUPButton")
        self.gridLayout_9.addWidget(self.pl11ASetIKUPButton, 3, 0, 1, 2)
        self.gridLayout_8.addWidget(self.pl11AIKUGBoxGrBox, 2, 0, 1, 2)
        self.pl11AInterfaceGrBox = QtWidgets.QGroupBox(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl11AInterfaceGrBox.sizePolicy().hasHeightForWidth())
        self.pl11AInterfaceGrBox.setSizePolicy(sizePolicy)
        self.pl11AInterfaceGrBox.setMinimumSize(QtCore.QSize(250, 0))
        self.pl11AInterfaceGrBox.setObjectName("pl11AInterfaceGrBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pl11AInterfaceGrBox)
        self.gridLayout_10.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_10.setSpacing(5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pl11ARdPButton = QtWidgets.QPushButton(self.pl11AInterfaceGrBox)
        self.pl11ARdPButton.setObjectName("pl11ARdPButton")
        self.gridLayout_10.addWidget(self.pl11ARdPButton, 10, 0, 1, 2)
        self.pl11ARdAddrLabel = QtWidgets.QLabel(self.pl11AInterfaceGrBox)
        self.pl11ARdAddrLabel.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11ARdAddrLabel.setFont(font)
        self.pl11ARdAddrLabel.setObjectName("pl11ARdAddrLabel")
        self.gridLayout_10.addWidget(self.pl11ARdAddrLabel, 5, 0, 1, 1)
        self.pl11AWrDataLabel = QtWidgets.QLabel(self.pl11AInterfaceGrBox)
        self.pl11AWrDataLabel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11AWrDataLabel.setFont(font)
        self.pl11AWrDataLabel.setObjectName("pl11AWrDataLabel")
        self.gridLayout_10.addWidget(self.pl11AWrDataLabel, 2, 0, 1, 1)
        self.pl11AWrAddrLabel = QtWidgets.QLabel(self.pl11AInterfaceGrBox)
        self.pl11AWrAddrLabel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11AWrAddrLabel.setFont(font)
        self.pl11AWrAddrLabel.setObjectName("pl11AWrAddrLabel")
        self.gridLayout_10.addWidget(self.pl11AWrAddrLabel, 0, 0, 1, 1)
        self.pl11ARdDataLabel = QtWidgets.QLabel(self.pl11AInterfaceGrBox)
        self.pl11ARdDataLabel.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11ARdDataLabel.setFont(font)
        self.pl11ARdDataLabel.setObjectName("pl11ARdDataLabel")
        self.gridLayout_10.addWidget(self.pl11ARdDataLabel, 8, 0, 1, 1)
        self.pl11AWrPButton = QtWidgets.QPushButton(self.pl11AInterfaceGrBox)
        self.pl11AWrPButton.setObjectName("pl11AWrPButton")
        self.gridLayout_10.addWidget(self.pl11AWrPButton, 4, 0, 1, 2)
        self.pl11ARdDataLEdit = QtWidgets.QLineEdit(self.pl11AInterfaceGrBox)
        self.pl11ARdDataLEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11ARdDataLEdit.setFont(font)
        self.pl11ARdDataLEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pl11ARdDataLEdit.setReadOnly(True)
        self.pl11ARdDataLEdit.setObjectName("pl11ARdDataLEdit")
        self.gridLayout_10.addWidget(self.pl11ARdDataLEdit, 8, 1, 1, 1)
        self.pl11ARdAddrLEdit = QtWidgets.QLineEdit(self.pl11AInterfaceGrBox)
        self.pl11ARdAddrLEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11ARdAddrLEdit.setFont(font)
        self.pl11ARdAddrLEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pl11ARdAddrLEdit.setObjectName("pl11ARdAddrLEdit")
        self.gridLayout_10.addWidget(self.pl11ARdAddrLEdit, 5, 1, 1, 1)
        self.pl11AWrDataLEdit = QtWidgets.QLineEdit(self.pl11AInterfaceGrBox)
        self.pl11AWrDataLEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11AWrDataLEdit.setFont(font)
        self.pl11AWrDataLEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pl11AWrDataLEdit.setObjectName("pl11AWrDataLEdit")
        self.gridLayout_10.addWidget(self.pl11AWrDataLEdit, 2, 1, 1, 1)
        self.pl11AWrAddrLEdit = QtWidgets.QLineEdit(self.pl11AInterfaceGrBox)
        self.pl11AWrAddrLEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pl11AWrAddrLEdit.setFont(font)
        self.pl11AWrAddrLEdit.setMaxLength(12)
        self.pl11AWrAddrLEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pl11AWrAddrLEdit.setObjectName("pl11AWrAddrLEdit")
        self.gridLayout_10.addWidget(self.pl11AWrAddrLEdit, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.pl11AInterfaceGrBox, 3, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 4, 0, 1, 2)
        self.PL11ALabel = QtWidgets.QLabel(self.mainTab)
        self.PL11ALabel.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PL11ALabel.setFont(font)
        self.PL11ALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PL11ALabel.setObjectName("PL11ALabel")
        self.gridLayout_8.addWidget(self.PL11ALabel, 0, 0, 1, 2)
        self.line_9 = QtWidgets.QFrame(self.mainTab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_8.addWidget(self.line_9, 1, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_8)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sendFlTaskPButton = QtWidgets.QPushButton(self.mainTab)
        self.sendFlTaskPButton.setObjectName("sendFlTaskPButton")
        self.gridLayout_4.addWidget(self.sendFlTaskPButton, 8, 0, 1, 1)
        self.writeFlTaskPButton = QtWidgets.QPushButton(self.mainTab)
        self.writeFlTaskPButton.setObjectName("writeFlTaskPButton")
        self.gridLayout_4.addWidget(self.writeFlTaskPButton, 9, 0, 1, 1)
        self.DCRModeDefaultPButton = QtWidgets.QPushButton(self.mainTab)
        self.DCRModeDefaultPButton.setMinimumSize(QtCore.QSize(120, 30))
        self.DCRModeDefaultPButton.setObjectName("DCRModeDefaultPButton")
        self.gridLayout_4.addWidget(self.DCRModeDefaultPButton, 3, 0, 1, 1)
        self.checkFlTaskPButton = QtWidgets.QPushButton(self.mainTab)
        self.checkFlTaskPButton.setObjectName("checkFlTaskPButton")
        self.gridLayout_4.addWidget(self.checkFlTaskPButton, 8, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.mainTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.mainTab)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 2)
        self.DCRModeFlightTaskPButton = QtWidgets.QPushButton(self.mainTab)
        self.DCRModeFlightTaskPButton.setMinimumSize(QtCore.QSize(120, 30))
        self.DCRModeFlightTaskPButton.setObjectName("DCRModeFlightTaskPButton")
        self.gridLayout_4.addWidget(self.DCRModeFlightTaskPButton, 3, 1, 1, 1)
        self.DCRModePausePButton = QtWidgets.QPushButton(self.mainTab)
        self.DCRModePausePButton.setMinimumSize(QtCore.QSize(120, 30))
        self.DCRModePausePButton.setObjectName("DCRModePausePButton")
        self.gridLayout_4.addWidget(self.DCRModePausePButton, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.mainTab)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 7, 0, 1, 2)
        self.DCRModeOffPButton = QtWidgets.QPushButton(self.mainTab)
        self.DCRModeOffPButton.setMinimumSize(QtCore.QSize(120, 30))
        self.DCRModeOffPButton.setObjectName("DCRModeOffPButton")
        self.gridLayout_4.addWidget(self.DCRModeOffPButton, 5, 1, 1, 1)
        self.DecorLabel = QtWidgets.QLabel(self.mainTab)
        self.DecorLabel.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DecorLabel.setFont(font)
        self.DecorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DecorLabel.setObjectName("DecorLabel")
        self.gridLayout_4.addWidget(self.DecorLabel, 0, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 10, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.mainTab, "")
        self.canTerminalTab = QtWidgets.QWidget()
        self.canTerminalTab.setObjectName("canTerminalTab")
        self.tabWidget.addTab(self.canTerminalTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openGraphPButton.setText(_translate("MainWindow", "Open Graphs"))
        self.logRestartPButt.setText(_translate("MainWindow", "Log Restart"))
        self.connectionPButt.setText(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Power channels"))
        self.channelGrBox.setTitle(_translate("MainWindow", "Channels"))
        self.allChannelsChBox.setText(_translate("MainWindow", "All"))
        self.pl11aChannelsChBox.setText(_translate("MainWindow", "PL1.1A"))
        self.pl11bChannelsChBox.setText(_translate("MainWindow", "PL1.1B"))
        self.pl12ChannelsChBox.setText(_translate("MainWindow", "PL1.2"))
        self.lmChannelsChBox.setText(_translate("MainWindow", "LM"))
        self.pl20ChannelsChBox.setText(_translate("MainWindow", "PL2.0"))
        self.dcr1ChannelsChBox.setText(_translate("MainWindow", "DCR1"))
        self.dcr2ChannelsChBox.setText(_translate("MainWindow", "DCR2"))
        self.pwrChsSetPButton.setText(_translate("MainWindow", "Set power channels state"))
        self.stopCyclsPButton.setText(_translate("MainWindow", "Stop Cyclograms"))
        self.startCyclsPButton.setText(_translate("MainWindow", "Start Cyclic Mode"))
        self.label_2.setText(_translate("MainWindow", "Cyclograms"))
        self.singleCyclPButton.setText(_translate("MainWindow", "Single Cyclograma"))
        self.label_3.setText(_translate("MainWindow", "General data"))
        self.genDataGetPButton.setText(_translate("MainWindow", "Get general data"))
        self.cycleReadGenDataPButton.setText(_translate("MainWindow", "Cycle get general_data"))
        self.pl11AIKUGBoxGrBox.setTitle(_translate("MainWindow", "IKU"))
        self.pl11AResetFPGAChBox.setText(_translate("MainWindow", "RESET_FPGA"))
        self.pl11AResetMCUChBox.setText(_translate("MainWindow", "RESEET_MCU"))
        self.pl11ASetIKUPButton.setText(_translate("MainWindow", "SET IKU"))
        self.pl11AInterfaceGrBox.setTitle(_translate("MainWindow", "Interface"))
        self.pl11ARdPButton.setText(_translate("MainWindow", "Read"))
        self.pl11ARdAddrLabel.setText(_translate("MainWindow", "Address (hex):"))
        self.pl11AWrDataLabel.setText(_translate("MainWindow", "Data (hex):"))
        self.pl11AWrAddrLabel.setText(_translate("MainWindow", "Address (hex):"))
        self.pl11ARdDataLabel.setText(_translate("MainWindow", "Data (hex):"))
        self.pl11AWrPButton.setText(_translate("MainWindow", "Write"))
        self.pl11ARdDataLEdit.setText(_translate("MainWindow", "0000 0000"))
        self.pl11ARdAddrLEdit.setText(_translate("MainWindow", "B000 0000"))
        self.pl11AWrDataLEdit.setText(_translate("MainWindow", "0000 0001"))
        self.pl11AWrAddrLEdit.setText(_translate("MainWindow", "B000 0000"))
        self.PL11ALabel.setText(_translate("MainWindow", "PL1.1_A"))
        self.sendFlTaskPButton.setText(_translate("MainWindow", "Send Test FT"))
        self.writeFlTaskPButton.setText(_translate("MainWindow", "Write Test FT"))
        self.DCRModeDefaultPButton.setText(_translate("MainWindow", "Default"))
        self.checkFlTaskPButton.setText(_translate("MainWindow", "Check Test FT"))
        self.label_5.setText(_translate("MainWindow", "Modes"))
        self.DCRModeFlightTaskPButton.setText(_translate("MainWindow", "FlightTask"))
        self.DCRModePausePButton.setText(_translate("MainWindow", "Pause"))
        self.label_4.setText(_translate("MainWindow", "Flight Task"))
        self.DCRModeOffPButton.setText(_translate("MainWindow", "Off"))
        self.DecorLabel.setText(_translate("MainWindow", "DeCoR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canTerminalTab), _translate("MainWindow", "Can terminal"))
